---
- name: install fake s3
  gem:
    name: fakes3
    state: present
    user_install: no

- name: copy fake s3 systemd unit file into place
  copy:
    src: fakes3.service
    dest: /etc/systemd/system/fakes3.service
    owner: root
    group: root

- name: ensure fake s3 is enabled
  systemd:
    name: fakes3
    state: started
    enabled: yes

- name: install s3cmd
  apt:
    package: s3cmd
    state: present
