---
- name: create ~/.ssh directory
  file:
    state: directory
    path: /home/deploy/.ssh
    mode: 0700

- name: copy ssh keys
  copy:
    content: "{{ deploy.deploy_key }}"
    dest: /home/deploy/.ssh/id_rsa
    mode: 0600
  when: deploy.deploy_key is defined

- name: enable ssh
  authorized_key:
    user: deploy
    state: present
    key: "{{ deploy.authorized_keys }}"
